import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import RootProvider from "@/components/providers/root-provider";
import { cn } from "@/utils/ui";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "NodeZEN • Best n8n Monitoring Dashboard",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      className={cn(geistSans.variable, geistMono.variable)}
      lang="en"
      suppressHydrationWarning
    >
      <body>
        <RootProvider>
          <main className="h-screen w-screen">{children}</main>
        </RootProvider>
      </body>
    </html>
  );
}
